### ISSUE TITLE
veeam-availability-console-grafana/Grafana Dashboard for Veeam Availability Console - Job History.json issue

### ISSUE THREAD

**Issue by johnfelipe** [VeeamHub/grafana#24]
https://drive.google.com/file/d/1GxES4mr7Ioqk_Ri2_KnXgiBiPs8tkmQn/view?usp=drivesdk

not working importing json file
https://drive.google.com/file/d/1fMgx1GD4U3NDQk4xzG6ozTQHTASrVYHE/view?usp=drivesdk

**Comment by johnfelipe** [comment]
anyone?

**Comment by 768kb** [comment]
Github is for Source Code, and issues here for issues found in the source code. If I understood you right, you have problems using the Code from here. You should do your own research and read the docs (from grafana etc). If you have found any issue in the source code, you can report it here. Github usually is not a support forum. 🙂 I don't mean to offend you, but to help you understand that this may be the wrong place for support requests.

Disclaimer: I am not from Veeam. This is my own oppinion.

**Comment by 768kb** [comment]
Or in other words: github is for free software from volunteers. Who now also expects that you get free support has not understood something in my opinion.

**Comment by nielsengelen** [comment]
As mentioned in the other issues, this script is used for the Veeam Service Provider Console. You did not confirm which one you are running (Enterprise Manager or the console) and therefor we cannot properly point you in any direction. I will close this issue due to a lack of proper information and unclear videos.
